const ENDPOINTS = {
  HOME: "/",
  LISTINGS: "/listings",
  PROFILE: "/profile",
  UPDATE_PROFILE: "/update-profile",
  SIGNUP: "/signup",
  SIGNIN: "/signin",
  ABOUT: "/about",
  SETTINGS: "/settings",
  CHANGE_PASSWORD: "/change-password",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password/:token",
  CREATE_LISTING: "/create-listing",
  USER_LISTING_DETAIL: "listing/:id",
  USER_LISTINGS: "/user-listings",
  EDIT_LISTING: "/edit-listing/:id",
  VERIFY_EMAIL: "/verify-email",
  VERIFY_PHONE_NUMBER: "/verify-phone-number",
};
export default ENDPOINTS;
